# Generated by Django 2.2 on 2019-04-12 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymodel',
            name='category_status',
            field=models.CharField(max_length=10),
        ),
    ]
