# Generated by Django 2.2 on 2019-04-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_subcategorymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='category_des',
            new_name='subcategory_des',
        ),
        migrations.RenameField(
            model_name='subcategorymodel',
            old_name='category_status',
            new_name='subcategory_status',
        ),
    ]
