# Generated by Django 2.2 on 2019-04-14 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_auto_20190414_0542'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=40)),
                ('des', models.TextField()),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.CategoryModel')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.SubcategoryModel')),
            ],
        ),
    ]
