# Generated by Django 2.2 on 2019-04-17 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_producttypemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMetarial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metrial_name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.CategoryModel')),
                ('product_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.ProductTypeModel')),
                ('subcategory', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Backend.SubcategoryModel')),
            ],
        ),
    ]
