# Generated by Django 2.2 on 2019-04-17 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_productmetarial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmetarial',
            old_name='metrial_name',
            new_name='metarial_name',
        ),
    ]
