# Generated by Django 2.2 on 2019-04-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_brandmodel_productsizemodel_productspecificationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
