# Generated by Django 2.2 on 2019-04-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_auto_20190420_1945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='templatemetarialchildmodel',
            old_name='metarial_id',
            new_name='metarial',
        ),
        migrations.RenameField(
            model_name='templatesizechildmodel',
            old_name='size_id',
            new_name='size',
        ),
        migrations.RenameField(
            model_name='templatespecificationchild',
            old_name='specification_id',
            new_name='specification',
        ),
    ]
